//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 02:27:11 PM IST 
//


package com.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="org-meta-data" type="{http://www.psltsk.com}orgMetaData"/>
 *         &lt;element name="s-objects" type="{http://www.psltsk.com}sObjectsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organization", propOrder = {
    "orgMetaData",
    "sObjects"
})
public class Organization {

    @XmlElement(name = "org-meta-data", required = true)
    protected OrgMetaData orgMetaData;
    @XmlElement(name = "s-objects", required = true)
    protected SObjectsType sObjects;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the orgMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link OrgMetaData }
     *     
     */
    public OrgMetaData getOrgMetaData() {
        return orgMetaData;
    }

    /**
     * Sets the value of the orgMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgMetaData }
     *     
     */
    public void setOrgMetaData(OrgMetaData value) {
        this.orgMetaData = value;
    }

    /**
     * Gets the value of the sObjects property.
     * 
     * @return
     *     possible object is
     *     {@link SObjectsType }
     *     
     */
    public SObjectsType getSObjects() {
        return sObjects;
    }

    /**
     * Sets the value of the sObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link SObjectsType }
     *     
     */
    public void setSObjects(SObjectsType value) {
        this.sObjects = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
