//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 02:27:11 PM IST 
//


package com.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="thresholds" type="{http://www.psltsk.com}thresholds"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settings", propOrder = {

})
public class Settings {

    @XmlElement(required = true)
    protected Thresholds thresholds;

    /**
     * Gets the value of the thresholds property.
     * 
     * @return
     *     possible object is
     *     {@link Thresholds }
     *     
     */
    public Thresholds getThresholds() {
        return thresholds;
    }

    /**
     * Sets the value of the thresholds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Thresholds }
     *     
     */
    public void setThresholds(Thresholds value) {
        this.thresholds = value;
    }

}
